version: '3.7'

services:
  nginx:
    container_name: nginx-angular
    image: nginx-angular
    build:
      context: .
      dockerfile: dockerfile.production
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - node
    networks:
      - app-network

  node:
    container_name: angular-node-service
    image: angular-node-service
    build:
      context: ./server
      dockerfile: node.dockerfile
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge